### ISSUE TITLE
Project Feedback - 박은진 (Spring Tutor)

### ISSUE THREAD

**Issue by iamzin** [verdureKo/Spring-Lv.2#1]

**Comment by iamzin** [comment]
JPA repository의 save method를 사용한 create method 에서는 @Transactional 없이도 DB에 데이터 반영이 잘 됩니다. 
(코드에는 작성해 주셨지만요.)
반면, update method는 @Transactional을 사용해야만 반영이 됩니다.
그 이유에 대해서 찾아보시면 좋을 것 같습니다. :)

https://github.com/verdureKo/Spring-Lv.2/blob/ec9c283502b2d32e75da4e3910342c8daa2482a4/src/main/java/com/sparta/blog/service/BlogService.java#L27-L39
https://github.com/verdureKo/Spring-Lv.2/blob/ec9c283502b2d32e75da4e3910342c8daa2482a4/src/main/java/com/sparta/blog/service/BlogService.java#L60-L79

**Comment by iamzin** [comment]
JPA Repository에 존재여부를 확인해주는 method도 있답니다. :)
existsBy 로 시작하니 찾아보시고 활용해보세요!
https://github.com/verdureKo/Spring-Lv.2/blob/ec9c283502b2d32e75da4e3910342c8daa2482a4/src/main/java/com/sparta/blog/service/UserService.java#L29-L32

**Comment by verdureKo** [comment]
JPA repository의 save method를 사용한 create method 에서 @transactional 삭제
Optional이 아닌 Repository에서 username 존재여부를 확인하는 existByUserName() 메소드로 변경

**Comment by verdureKo** [comment]
![image](https://github.com/verdureKo/Spring-Lv.2/assets/133493520/4f73dea7-fa6e-4e0f-8cc5-ae076938b538)
PostMan으로 create확인
